[versions]
agp = "7.3.1"
kotlin = "1.7.22"
hilt = "2.44.2"
material = "1.7.0"
androidxCoreKtx = "1.9.0"
androidxAppcompat = "1.5.1"
junit = "4.13.2"
turbine = "0.12.1"
androidxTest = "1.5.0"
mockitoKotlin = "2.2.0"
mockitoInline = "3.12.4"
coroutines = "1.6.4"
truth = "1.1.3"
androidxTestJunit = "1.1.4"
espresso = "3.5.0"
androidTestRunner = "1.3.0-beta01"
androidxFragment = "1.5.5"
androidxLifecycle = "2.5.1"
androidXStartup = "1.1.1"
recyclerView = "1.2.1"
baseAdapter = "1.0.4"
whatIf = "1.1.1"
bindables = "1.1.0"
bundler = "1.0.4"
progressView = "1.1.3"
androidxConstraintlayout = "2.1.4"

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.12.0" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt-plugin = { id = "dagger.hilt.android.plugin", version = "hilt" }

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }

# androidx
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-corektx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidXStartup" }

# data binding
bindables = { module = "com.github.skydoves:bindables", version.ref = "bindables" }

# di
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# whatIf
whatif = { module = "com.github.skydoves:whatif", version.ref = "whatIf" }

# bundler
bundler = { module = "com.github.skydoves:bundler", version.ref = "bundler" }

# customViews
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
baseAdapter = { module = "com.github.skydoves:baserecyclerviewadapter", version.ref = "baseAdapter" }
progressView = { module = "com.github.skydoves:progressview", version.ref = "progressView" }

# unit test
junit = { module = "junit:junit", version.ref = "junit" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
mockito-kotlin  = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockito-inline  = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
android-test-runner = { module = "com.android.support.test:runner", version.ref = "androidTestRunner" }